name: digicard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_themes: ^0.3.12
  envied: ^0.5.4+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.2.19
  google_fonts: ^6.1.0
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.5
  http_parser: ^4.0.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  universal_io: ^2.2.0
  universal_html: ^2.2.1
  mime: ^1.0.4
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  intl: ^0.19.0
  rename: ^3.0.2
  shared_preferences: ^2.0.13
  logger: ^2.4.0
  path: ^1.8.2
  path_provider: ^2.0.11
  validators: ^3.0.0
  equatable: ^2.0.3
  url_launcher: ^6.1.2
  uuid: ^4.4.2
  faker: ^2.0.0
  collection: ^1.17.0
  cached_memory_image: ^1.3.1
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.3.0
  auto_size_text: ^3.0.0
  loader_overlay: ^4.0.0
  cached_network_image: ^3.2.0
  image_downloader_web: ^2.0.4
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.1
  reactive_forms: 17.0.1
  reactive_forms_annotations: 5.0.0
  reactive_date_time_picker: ^3.0.0
  reactive_image_picker: ^5.0.0
  flutter_contacts: ^1.1.7+1
  supabase_flutter: ^2.5.8
  uni_links: ^0.5.1
  fluttertoast: ^8.2.4
  another_transformer_page_view: ^2.0.1
  smooth_page_indicator: ^1.1.0
  reactive_color_picker: ^2.0.0
  flutter_intro: ^3.0.3
  reactive_links_picker:
    path: packages/reactive_links_picker
  reactive_layout_picker:
    path: packages/reactive_layout_picker
  reactive_image_picker_universal:
    path: packages/reactive_image_picker_universal
  flutter_ez_core:
    path: packages/flutter_ez_core
  easy_debounce: ^2.0.3
dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0-pre.1
  reactive_forms_generator: 5.0.4
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  analyzer: ^6.4.1
  envied_generator: ^0.5.4+1
  dependency_validator: ^4.1.0
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
  
dependency_overrides:
  image_picker_android: 0.8.4+13
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - google_fonts/
  uses-material-design: true


